# Jekyll config file
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: DRAFT Swiss profile 2.0 for NeTEx 2.0
email: info.fachbus@sbb.ch
description: >- # this means to ignore newlines until "baseurl:"
  This document describes the realisation specifications for the data transfer between SKI and the public transport in 
  Switzerland, based on the official NeTEx standard.
# baseurl:  is now set during the build, e.g. to /netexRealisationGuideSwitzerland/main = subpath of your site, e.g. /blog
domain: opentdatach.github.io
url: https://opentdatach.github.io # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled: true
  strip_title: true # remove the first heading from the body once used as the title
  collections: true # also apply to posts/collections

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: with-sidebar
