# Builds the docs and deploys them to GitHub pages.
name: Build and deploy to Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Workflow run composed of build and deploy jobs
jobs:

  # Builds and uploads artifact for GitHib pages
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks out git repository
      - uses: actions/checkout@v4

      # Builds tools and generates md docs under ./site
      - name: Build tools and generate md docs
        run: |
          ./tools/build.sh

      # Builds static html web pages with jekyll under ./site
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install bundler and gems for jekyll
        run: |
          cd site
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Build static html web page with jekyll
        run: |
          cd site
          ls Gemfile
          bundle exec jekyll build

      # Creates and uploads the build artifact from ./site
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site/_site

  # Deploys artifact to GitHub pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
